apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: myapp-service
  description: MyApp Api
  tags:
    - nodejs
spec:
  type: service
  lifecycle: experimental
  owner: user:guest
  providesApis:
    - myapp-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: myapp-api
  description: MyApp OpenAPI
spec:
  type: openapi
  lifecycle: experimental
  owner: user:guest
  definition:
    $text: ./openapi.yaml