apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: openapi-sample-service
  description: Sample service exposing an OpenAPI API
  tags:
    - nodejs
    - example
spec:
  type: service
  lifecycle: experimental
  owner: user:guest
  providesApis:
    - openapi-sample-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: openapi-sample-api
  description: Sample OpenAPI for Backstage
spec:
  type: openapi
  lifecycle: experimental
  owner: user:guest
  definition:
    $text: ./openapi.yaml